pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"

  - task: Npm@1
    displayName: "Install Gatsby-cli"
    inputs:
      command: custom
      customCommand: install --global gatsby-cli
  
  - task: Npm@1
    displayName: "Instaling Node Modules"
    inputs:
      command: install

  - task: Npm@1
    displayName: "Create production distribution"
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    inputs:
      command: custom
      customCommand: run build
      workingDir: $(System.DefaultWorkingDirectory)
  
  - task: Npm@1
    displayName: "Create croneri-azure-setup distribution"
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'croneri-azure-setup'))
    inputs:
      command: custom
      customCommand: run build
      workingDir: $(System.DefaultWorkingDirectory)

  - task: CopyFiles@2
    displayName: ‘Copy Progression Framework Artifact’
    inputs:
      Contents: |
        public/**/*
        terraform/**/*
      targetFolder: $(Build.ArtifactStagingDirectory)

  - publish: $(Build.ArtifactStagingDirectory)
    displayName: 'Publish Artifact.'
    artifact: croner-i-progression-framework

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 
      Contents: '**/*'
      RemoveDotFiles: true

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Artifact'
    inputs:
      buildType: 'current'
      targetPath: '$(Build.SourcesDirectory)'

  - task: AzureStaticWebApp@0
    displayName: 'Deploy Static Web App'
    inputs:
      app_location: 'croner-i-progression-framework'
      skip_app_build: true
      azure_static_web_apps_api_token: '$(deploy-token)'